# Generated by Django 2.2.12 on 2021-04-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduce',
            name='profile',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='introduce',
            name='detail',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='detail',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='techStack',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='thumbnail',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.TextField(blank=True, default='https://github.com/4Moyede/', null=True),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='skill',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='tech',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
