# Generated by Django 2.2.12 on 2021-04-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210408_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduce',
            name='picture',
            field=models.TextField(default='profile.jpeg'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='thumbnail',
            field=models.TextField(blank=True, default='loading.png', null=True),
        ),
    ]
