# Generated by Django 2.2.12 on 2021-04-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210414_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduce',
            name='picture',
            field=models.TextField(default='favicon.ico'),
        ),
    ]
